name: Intakes and CSV Smokes

on:
  # Allow manual runs when permitted
  workflow_dispatch: {}
  # Run on any branch push so feature branches trigger CI
  push:
    branches: [ "**" ]
  # Also run on PRs targeting main
  pull_request:
    branches: [ main ]

jobs:
  smokes:
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_CONVEX_URL: ${{ secrets.NEXT_PUBLIC_CONVEX_URL }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run Intakes smoke (SDK)
        if: ${{ env.NEXT_PUBLIC_CONVEX_URL != '' }}
        run: pnpm smoke:intakes

      - name: Run CSV/Uploads smoke (HTTP)
        if: ${{ env.NEXT_PUBLIC_CONVEX_URL != '' }}
        run: pnpm smoke:csv

      - name: Skip notice (missing NEXT_PUBLIC_CONVEX_URL)
        if: ${{ env.NEXT_PUBLIC_CONVEX_URL == '' }}
        run: echo Skipping smokes - NEXT_PUBLIC_CONVEX_URL not set
